project:
  type: website

website:
  navbar:
    search: false
    right:
      - text: "HOME"
        href: index.qmd
      - text: "ABOUT"
        href: about.qmd
      - text: "POSTS"
        href: posts.qmd
      - text: "CONTACT"
        href: contact.qmd
  page-footer:
    center: 
      - icon: linkedin
        href: https://linkedin.com
      - icon: mastodon
        href: https://mastodon.social
      - icon: envelope
        href: mailto:your-email@example.com
      - icon: github
        href: https://github.com/

format:
  html:
    theme: sketchy
    css: styles.css





